export const START_COMBAT = 'START_COMBAT';
export const RESOLVE_CARD = 'RESOLVE_CARD';
export const RESOLVE_MONSTER_ACTION = 'RESOLVE_MONSTER_ACTION';
export const START_NEXT_TURN = 'START_NEXT_TURN';
export const ACCEPT_REWARD = 'ACCEPT_REWARD';
export const RESET_COMBAT = 'RESET_COMBAT';